# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe5baa57dad61ccc6cb7874c2c04bf5c8e1f0c4fd701547dc0197cfbd34ce1d62ab8c073b8d0f730132c1e2d54ab5064cf1c9a93d8abbe0554537fb7e215fcd

test:
  secret_key_base: 26b1e4fb2e5bf30ae473e2381885028826eb9854fe5ceab80f2d3f27e03933785b191f83a5a2049702dbac3d8e50aa95a228ffa19cea8e9591d71a0ddf0be80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
